// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAc0IycHm7kaKoW67rUVLENNJllN1z5Wzc',
    appId: '1:268111542837:web:PLACEHOLDER',
    messagingSenderId: '268111542837',
    projectId: 'trendly-c0cf5',
    authDomain: 'trendly-c0cf5.firebaseapp.com',
    storageBucket: 'trendly-c0cf5.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAc0IycHm7kaKoW67rUVLENNJllN1z5Wzc',
    appId: '1:268111542837:android:2a23aca01a5a1aa89fcf7c',
    messagingSenderId: '268111542837',
    projectId: 'trendly-c0cf5',
    storageBucket: 'trendly-c0cf5.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDCr0Ht7mt92Pr343b-BE6qj6z_yDBHWHs',
    appId: '1:268111542837:ios:efd6137ba38983469fcf7c',
    messagingSenderId: '268111542837',
    projectId: 'trendly-c0cf5',
    storageBucket: 'trendly-c0cf5.firebasestorage.app',
    iosBundleId: 'net.lamoss.trendly',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDCr0Ht7mt92Pr343b-BE6qj6z_yDBHWHs',
    appId: '1:268111542837:ios:efd6137ba38983469fcf7c',
    messagingSenderId: '268111542837',
    projectId: 'trendly-c0cf5',
    storageBucket: 'trendly-c0cf5.firebasestorage.app',
    iosBundleId: 'net.lamoss.trendly',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAc0IycHm7kaKoW67rUVLENNJllN1z5Wzc',
    appId: '1:268111542837:web:PLACEHOLDER',
    messagingSenderId: '268111542837',
    projectId: 'trendly-c0cf5',
    authDomain: 'trendly-c0cf5.firebaseapp.com',
    storageBucket: 'trendly-c0cf5.firebasestorage.app',
  );
}